### ISSUE TITLE
appreciate the time/effort

### ISSUE THREAD

**Issue by duhaas2015** [johnsarie27/AWSAutomation#6]
looking to leverage this automation, but keep running into a situation where running:
Remove-LapsedAMI -ProfileName tst2 -Region us-east-2 -BackupSuffix '' -DailyBackupRetentionPeriod 30 -RunAsTestOnly:$false

all it does it displays what it would of removed, doesn't actually issue the commands inside:
```
            # SETUP SPLATTER TABLE FOR PARAMETERS
            $Splat.Remove('Owner'); $Splat['bolRunAsTestOnly'] = $RunAsTestOnly

            # UNREGISTER AMIS
            if ( $DailyImagesToDelete ) { Unregister-EC2AmisandSnapshot @Splat -amisTargetedForDeletion $DailyImagesToDelete }
            if ( $WeeklyImagesToDelete ) { Unregister-EC2AmisandSnapshot @Splat -amisTargetedForDeletion $WeeklyImagesToDelete }
            if ( $MonthlyImagesToDelete ) { Unregister-EC2AmisandSnapshot @Splat -amisTargetedForDeletion $MonthlyImagesToDelete }
```

**Comment by johnsarie27** [comment]
Hi duhaas2015,

Sorry for the slow response. I started this project for myself and didn't realize anyone else was actually using it.  Try using the parameter and argument "-RunAsTestOnly $false" and see if that fixes your issue.  Hope that helps.

PS - I've also gotten away from using AMI's and started using more of AWS' EBS Lifecycle Policies. They've made good improvements over the past several months.
